### PR TITLE
Added UML with client and server architecture.

### PR DESCRIPTION
**Pull request by blairjam**
@jcarter95 @brandonrmitchell 
I've got the 5 main pages with are handled be the client. Then there is the server which handles 3 objects for database access, matching algorithm, and email notifications. 

What do you think?

### CODE REVIEW

**Comment by jcarter95** [comment]
Looks good. With this being finished, what does that leave us left to do?

**Comment by jcarter95** [comment]
Also, is this issue ready to be closed?

**Comment by blairjam** [comment]
Yeah, I'll close it in just a second. #24

**Comment by blairjam** [comment]
I think all that the front end has left is Brandon's part, D3.

**Comment by blairjam** [comment]
But, with the amount of mess that this milestone is, I'm sure Tyler wouldn't mind help on whatever they have left too.

**Pull request merged**
